---
- hosts: jump_hosts
  become: yes
  tasks:
    - name: Edit index file
      lineinfile:
        path: /var/www/html/index.html
        line: "I'm back"
      when:
        - ansible_hostname == "ftd-gcloud01"

