---
- hosts: jump_hosts
  become: true
  tasks:
    - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
      cron:
        name: "check dirs"
        minute: "0"
        hour: "5,5"
        job: "df -h >> /tmp/diskspace"
   
