---
- hosts: jump_hosts
  become: yes
  tasks:
    - name: install apache
      yum: 
        name: httpd
        state: latest
    - name: Check apache is properly installed
      yum:  
        list: httpd
    - name: start and enable httpd
      service: 
        name: httpd
        state: started
        enabled: yes
    - name: create index.html
      file:
        path: /var/www/html/index.html
        state: touch   
    - name: Add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: 'Hello World'

        
